import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Inter_Tight,
  Noto_Kufi_Arabic,
} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Headers from "@/components/header/Headers";
import Footer from "@/components/footer/Footer";

const kufiArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
});
const InterFont = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Next 14 Tutorial",
  description: "Generated by Mahdi Alsholi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={InterFont.className}>
        <Headers />
        <main className="fix-height">{children}</main>
        <Footer  />
      </body>
    </html>
  );
}
